sudo: required
services:
    - docker

before_install:
    - docker build -t ziyank/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true ziyank/react-test npm test

after_success:
    - docker build -t ziyank/multi-client ./client
    - docker build -t ziyank/multi-nginx ./nginx
    - docker build -t ziyank/multi-server ./server
    - docker build -t ziyank/multi-worker ./worker
    #Logging into docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ziyank/multi-client 
    - docker push ziyank/multi-nginx 
    - docker push ziyank/multi-server 
    - docker push ziyank/multi-worker 